# Generated by Django 3.0.6 on 2020-06-11 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.AddField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
