# Generated by Django 3.0.6 on 2020-06-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200611_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_added',
            new_name='date',
        ),
    ]
