# Generated by Django 3.0.6 on 2020-06-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='side/images/')),
                ('url_1', models.URLField()),
                ('url_2', models.URLField(blank=True)),
                ('url_3', models.URLField(blank=True)),
                ('url_4', models.URLField(blank=True)),
                ('url_5', models.URLField(blank=True)),
                ('url_6', models.URLField(blank=True)),
                ('url_7', models.URLField(blank=True)),
                ('url_8', models.URLField(blank=True)),
                ('url_9', models.URLField(blank=True)),
                ('url_10', models.URLField(blank=True)),
                ('url_11', models.URLField(blank=True)),
                ('url_12', models.URLField(blank=True)),
                ('blog_image', models.ImageField(null=True, upload_to='side/images/')),
            ],
        ),
    ]
