# Generated by Django 3.0.6 on 2020-06-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('side', '0002_remove_side_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='side',
            name='url_10',
        ),
        migrations.RemoveField(
            model_name='side',
            name='url_11',
        ),
        migrations.RemoveField(
            model_name='side',
            name='url_12',
        ),
        migrations.RemoveField(
            model_name='side',
            name='url_2',
        ),
        migrations.RemoveField(
            model_name='side',
            name='url_3',
        ),
        migrations.RemoveField(
            model_name='side',
            name='url_4',
        ),
        migrations.RemoveField(
            model_name='side',
            name='url_5',
        ),
        migrations.RemoveField(
            model_name='side',
            name='url_6',
        ),
        migrations.RemoveField(
            model_name='side',
            name='url_7',
        ),
        migrations.RemoveField(
            model_name='side',
            name='url_8',
        ),
        migrations.RemoveField(
            model_name='side',
            name='url_9',
        ),
    ]
