# Generated by Django 3.0.6 on 2020-06-11 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('side', '0003_auto_20200609_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='side',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
