# Generated by Django 3.0.6 on 2020-06-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('side', '0004_side_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='side',
            old_name='date_added',
            new_name='date',
        ),
    ]
